name: Cleanup old Vercel deployments

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  vercel-cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i -g vercel
      - run: vercel rm moddermore --safe --yes --token="$VERCEL_TOKEN"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
